---
title: "TIL: Week 11 In-Class Exercise"
description: |
  Today I learnt in class: How to build a R Shiny app. 
author:
  - name: Kelly Koh
    url: https://www.linkedin.com/in/kellykkw/
    affiliation: School of Computing and Information Systems, Singapore Management University
    affiliation_url: https://scis.smu.edu.sg/
date: 07-17-2021
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
    self_contained: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.retina = 3,
                      echo = TRUE,
                      eval = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

## Set Up a R Shiny App 

```{r}
library(shiny)
library(tidyverse)

exam <- read_csv("data/Exam_data.csv")

# Define UI for application 
ui <- fluidPage(
    titlePanel("Pupils Examination Results Dashboard"),
    sidebarLayout(
        sidebarPanel(
            selectInput(inputId = "variable",
                        label = "Subject: ",
                        choices = c("English" = "ENGLISH", 
                                    "Math" = "MATHS", 
                                    "Science" = "SCIENCE"),
                        selected = "ENGLISH"),
            sliderInput(inputId = "bin",
                        label = "Number of bins",
                        min = 5,
                        max = 20,
                        value = c(10)),
            checkboxInput(inputId = "show_data",
                          label = "Show data table",
                          value = TRUE)
        ),
        mainPanel(
            plotOutput("distplot"),
            DT::dataTableOutput(outputId = "examtable")
        )
    )
)

# Define server logic 
server <- function(input, output) {
    output$distplot <- renderPlot({
        x <- unlist(exam[,input$variable])
        ggplot(exam, aes(x)) +
            geom_histogram(bins = input$bin,
                           color = "black",
                           fill = "light blue")
    })
    
    output$examtable <- DT::renderDataTable({
        if(input$show_data){
            DT::datatable(data = exam %>%
                          select(1:7),
                          options = list(pageLength = 10),
                          rownames = FALSE)
        }
    })
}

# Run the application 
shinyApp(ui = ui, server = server)

```

