---
title: "Week 10 In-Class Exercise"
description: |
  Today I learnt in class: How to use graph analytics to represent relationships and finding connected components. 
author:
  - name: Kelly Koh
    url: https://www.linkedin.com/in/kellykkw/
    affiliation: School of Computing and Information Systems, Singapore Management University
    affiliation_url: https://scis.smu.edu.sg/
date: 07-03-2021
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Install packages and loading data

### Install the necessary packages if they are not in library
```{r echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('tidyverse',
             # Handling time variables
             'lubridate','clock',
             # Network graphing
             'network','igraph','tidygraph','ggraph','visNetwork')

for (p in packages) {
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

## Data cleaning

### Import data from csv and preview data
```{r echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}
cc_data <- read_csv("data/cc_data.csv")
GAStech_edges <- read_csv("data/GAStech_email_edge-v2.csv")
GAStech_nodes <- read_csv("data/GAStech_email_node.csv")

glimpse(GAStech_edges)
glimpse(GAStech_nodes)
```
SentDate is treated as "Character" data type instead of date type, which needs to be corrected.

### Change the format type of SentDate and add a new Weekday field
```{r echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}
GAStech_edges$SentDate = lubridate::dmy(GAStech_edges$SentDate)
GAStech_edges$Weekday = lubridate::wday(GAStech_edges$SentDate,
                             label = TRUE,
                             abbr = FALSE)

glimpse(GAStech_edges)
```


### vv
```{r echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}
GAStech_edges_aggregated <- GAStech_edges %>%
                            filter(MainSubject == "Work related")  %>%
                            group_by(source, target, Weekday) %>%
                            summarise(Weight = n())  %>%
                            filter(source != target)  %>%
                            filter(Weight > 1)  %>%
                            # Any time we do a group_by, we should do an ungroup
                            ungroup()
glimpse(GAStech_edges_aggregated)
```


### vv
```{r echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}

```


### vv
```{r echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}

```


### vv
```{r echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}

```

